services:
  app:
    build: .
    container_name: jobtrace-app
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: 5432
      POSTGRES_HOST: postgres
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

  prometheus:
    image: prom/prometheus:latest
    container_name: jobtrace-prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
      - "jobtrace_prometheus_data:/prometheus"
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: jobtrace-grafana
    ports:
      - "3000:3000"
    volumes:
      - "jobtrace_grafana_data:/var/lib/grafana"
    depends_on:
      - prometheus

  loki:
    image: grafana/loki:latest
    container_name: jobtrace-loki
    ports:
      - "3100:3100"
    volumes:
      - "jobtrace_loki_data:/loki"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    container_name: jobtrace-promtail
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./promtail-config.yml:/etc/promtail/config.yml"
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

  postgres:
    image: postgres:16
    container_name: jobtrace-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - "jobtrace_pgdata:/var/lib/postgresql/data"
      - "./docker/init-test-db.sql:/docker-entrypoint-initdb.d/init-test-db.sql"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  jobtrace_pgdata:
  jobtrace_prometheus_data:
  jobtrace_grafana_data:
  jobtrace_loki_data:
